version: '3.9'

services:
  mysql:
    platform: linux/amd64
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    restart: always
    hostname: mysql
    container_name: orginfo_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=g#Y!298mKwz85
      - MYSQL_USER=user
      - MYSQL_DATABASE=orginfo
